"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 The Jumpstarter Authors
(-- api-linter: core::0215::foreign-type-reference=disabled
(-- api-linter: core::0192::has-comments=disabled
(-- api-linter: core::0191::java-package=disabled
(-- api-linter: core::0191::java-outer-classname=disabled
(-- api-linter: core::0191::java-multiple-files=disabled
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import jumpstarter.v1.common_pb2
import jumpstarter.v1.kubernetes_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Exporter(google.protobuf.message.Message):
    """An exporter resource representing a registered device provider."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class DeprecatedLabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    ONLINE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    STATUS_MESSAGE_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    DEPRECATED_LABELS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the exporter."""
    online: builtins.bool
    """Whether the exporter is currently online. Deprecated in favor of the status field."""
    status: jumpstarter.v1.common_pb2.ExporterStatus.ValueType
    """The current status of the exporter."""
    status_message: builtins.str
    """A human-readable message providing details about the exporter status."""
    enabled: builtins.bool
    """Whether the exporter is enabled for lease assignment.
    When false, the controller will not assign new leases to this exporter.
    """
    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """The set of labels associated with the exporter."""

    @property
    def deprecated_labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Label keys on this exporter that the controller has marked as deprecated.
        Keys are the deprecated label names; values are optional human-readable messages.
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        online: builtins.bool = ...,
        status: jumpstarter.v1.common_pb2.ExporterStatus.ValueType = ...,
        status_message: builtins.str = ...,
        enabled: builtins.bool | None = ...,
        deprecated_labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_enabled", b"_enabled", "enabled", b"enabled"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_enabled", b"_enabled", "deprecated_labels", b"deprecated_labels", "enabled", b"enabled", "labels", b"labels", "name", b"name", "online", b"online", "status", b"status", "status_message", b"status_message"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_enabled", b"_enabled"]) -> typing.Literal["enabled"] | None: ...

Global___Exporter: typing_extensions.TypeAlias = Exporter

@typing.final
class Lease(google.protobuf.message.Message):
    """A lease resource representing a reservation of an exporter."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class ContextEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class DeprecatedLabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    SELECTOR_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    EFFECTIVE_DURATION_FIELD_NUMBER: builtins.int
    BEGIN_TIME_FIELD_NUMBER: builtins.int
    EFFECTIVE_BEGIN_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    EFFECTIVE_END_TIME_FIELD_NUMBER: builtins.int
    CLIENT_FIELD_NUMBER: builtins.int
    EXPORTER_FIELD_NUMBER: builtins.int
    CONDITIONS_FIELD_NUMBER: builtins.int
    EXPORTER_NAME_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    ALLOW_DISABLED_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    DEPRECATED_LABELS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the lease."""
    selector: builtins.str
    """The label selector expression used to match an exporter."""
    client: builtins.str
    """The resource name of the client that owns this lease."""
    exporter: builtins.str
    """The resource name of the exporter assigned to this lease."""
    exporter_name: builtins.str
    """The name of a specific exporter to target for the lease."""
    allow_disabled: builtins.bool
    """Allow leasing a disabled exporter. Only effective when exporter_name is set.
    Useful for investigating broken exporters that have been administratively disabled.
    """
    @property
    def duration(self) -> google.protobuf.duration_pb2.Duration:
        """The requested duration of the lease."""

    @property
    def effective_duration(self) -> google.protobuf.duration_pb2.Duration:
        """The server-computed effective duration of the lease."""

    @property
    def begin_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The requested begin time of the lease."""

    @property
    def effective_begin_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The server-computed effective begin time of the lease."""

    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The requested end time of the lease."""

    @property
    def effective_end_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The server-computed effective end time of the lease."""

    @property
    def conditions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[jumpstarter.v1.kubernetes_pb2.Condition]:
        """The list of conditions reflecting the current state of the lease."""

    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """The set of tags associated with the lease."""

    @property
    def context(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """User-defined context metadata for the lease (e.g. build_id, image_digest, VCS ref)."""

    @property
    def deprecated_labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Selector keys on this lease that the controller has marked as deprecated.
        Keys are the deprecated label names; values are optional human-readable messages.
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        selector: builtins.str = ...,
        duration: google.protobuf.duration_pb2.Duration | None = ...,
        effective_duration: google.protobuf.duration_pb2.Duration | None = ...,
        begin_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        effective_begin_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        effective_end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        client: builtins.str | None = ...,
        exporter: builtins.str | None = ...,
        conditions: collections.abc.Iterable[jumpstarter.v1.kubernetes_pb2.Condition] | None = ...,
        exporter_name: builtins.str | None = ...,
        tags: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        allow_disabled: builtins.bool = ...,
        context: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        deprecated_labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_begin_time", b"_begin_time", "_client", b"_client", "_duration", b"_duration", "_effective_begin_time", b"_effective_begin_time", "_effective_end_time", b"_effective_end_time", "_end_time", b"_end_time", "_exporter", b"_exporter", "_exporter_name", b"_exporter_name", "begin_time", b"begin_time", "client", b"client", "duration", b"duration", "effective_begin_time", b"effective_begin_time", "effective_duration", b"effective_duration", "effective_end_time", b"effective_end_time", "end_time", b"end_time", "exporter", b"exporter", "exporter_name", b"exporter_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_begin_time", b"_begin_time", "_client", b"_client", "_duration", b"_duration", "_effective_begin_time", b"_effective_begin_time", "_effective_end_time", b"_effective_end_time", "_end_time", b"_end_time", "_exporter", b"_exporter", "_exporter_name", b"_exporter_name", "allow_disabled", b"allow_disabled", "begin_time", b"begin_time", "client", b"client", "conditions", b"conditions", "context", b"context", "deprecated_labels", b"deprecated_labels", "duration", b"duration", "effective_begin_time", b"effective_begin_time", "effective_duration", b"effective_duration", "effective_end_time", b"effective_end_time", "end_time", b"end_time", "exporter", b"exporter", "exporter_name", b"exporter_name", "name", b"name", "selector", b"selector", "tags", b"tags"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_begin_time", b"_begin_time"]) -> typing.Literal["begin_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_client", b"_client"]) -> typing.Literal["client"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_duration", b"_duration"]) -> typing.Literal["duration"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_effective_begin_time", b"_effective_begin_time"]) -> typing.Literal["effective_begin_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_effective_end_time", b"_effective_end_time"]) -> typing.Literal["effective_end_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_end_time", b"_end_time"]) -> typing.Literal["end_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_exporter", b"_exporter"]) -> typing.Literal["exporter"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_exporter_name", b"_exporter_name"]) -> typing.Literal["exporter_name"] | None: ...

Global___Lease: typing_extensions.TypeAlias = Lease

@typing.final
class GetExporterRequest(google.protobuf.message.Message):
    """Request to retrieve an exporter."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    SHOW_HIDDEN_LABELS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the exporter."""
    show_hidden_labels: builtins.bool
    """When true, include labels hidden by controller configuration."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        show_hidden_labels: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "show_hidden_labels", b"show_hidden_labels"]) -> None: ...

Global___GetExporterRequest: typing_extensions.TypeAlias = GetExporterRequest

@typing.final
class ListExportersRequest(google.protobuf.message.Message):
    """Request to list exporters."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    SHOW_HIDDEN_LABELS_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The parent resource name (namespace)."""
    page_size: builtins.int
    """Maximum number of results to return."""
    page_token: builtins.str
    """Token for retrieving the next page of results."""
    filter: builtins.str
    """Filter expression for the results."""
    show_hidden_labels: builtins.bool
    """When true, include labels hidden by controller configuration."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
        show_hidden_labels: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filter", b"filter", "page_size", b"page_size", "page_token", b"page_token", "parent", b"parent", "show_hidden_labels", b"show_hidden_labels"]) -> None: ...

Global___ListExportersRequest: typing_extensions.TypeAlias = ListExportersRequest

@typing.final
class ListExportersResponse(google.protobuf.message.Message):
    """Response containing a list of exporters."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPORTERS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """Token for the next page of results."""
    @property
    def exporters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Exporter]:
        """The list of exporters."""

    def __init__(
        self,
        *,
        exporters: collections.abc.Iterable[Global___Exporter] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["exporters", b"exporters", "next_page_token", b"next_page_token"]) -> None: ...

Global___ListExportersResponse: typing_extensions.TypeAlias = ListExportersResponse

@typing.final
class GetLeaseRequest(google.protobuf.message.Message):
    """Request to retrieve a lease."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the lease."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

Global___GetLeaseRequest: typing_extensions.TypeAlias = GetLeaseRequest

@typing.final
class ListLeasesRequest(google.protobuf.message.Message):
    """Request to list leases."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    ONLY_ACTIVE_FIELD_NUMBER: builtins.int
    TAG_FILTER_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The parent resource name (namespace)."""
    page_size: builtins.int
    """Maximum number of results to return."""
    page_token: builtins.str
    """Token for retrieving the next page of results."""
    filter: builtins.str
    """Filter expression for the results."""
    only_active: builtins.bool
    """If true, return only active leases."""
    tag_filter: builtins.str
    """Filter expression for lease tags."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
        only_active: builtins.bool | None = ...,
        tag_filter: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_only_active", b"_only_active", "only_active", b"only_active"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_only_active", b"_only_active", "filter", b"filter", "only_active", b"only_active", "page_size", b"page_size", "page_token", b"page_token", "parent", b"parent", "tag_filter", b"tag_filter"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_only_active", b"_only_active"]) -> typing.Literal["only_active"] | None: ...

Global___ListLeasesRequest: typing_extensions.TypeAlias = ListLeasesRequest

@typing.final
class ListLeasesResponse(google.protobuf.message.Message):
    """Response containing a list of leases."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEASES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """Token for the next page of results."""
    @property
    def leases(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Lease]:
        """The list of leases."""

    def __init__(
        self,
        *,
        leases: collections.abc.Iterable[Global___Lease] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["leases", b"leases", "next_page_token", b"next_page_token"]) -> None: ...

Global___ListLeasesResponse: typing_extensions.TypeAlias = ListLeasesResponse

@typing.final
class CreateLeaseRequest(google.protobuf.message.Message):
    """Request to create a lease."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    LEASE_ID_FIELD_NUMBER: builtins.int
    LEASE_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The parent resource name (namespace)."""
    lease_id: builtins.str
    """The client-assigned identifier for the lease."""
    @property
    def lease(self) -> Global___Lease:
        """The lease resource to create."""

    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        lease_id: builtins.str = ...,
        lease: Global___Lease | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["lease", b"lease"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["lease", b"lease", "lease_id", b"lease_id", "parent", b"parent"]) -> None: ...

Global___CreateLeaseRequest: typing_extensions.TypeAlias = CreateLeaseRequest

@typing.final
class UpdateLeaseRequest(google.protobuf.message.Message):
    """Request to update a lease."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEASE_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def lease(self) -> Global___Lease:
        """The lease resource with updated fields."""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """The set of fields to update."""

    def __init__(
        self,
        *,
        lease: Global___Lease | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["lease", b"lease", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["lease", b"lease", "update_mask", b"update_mask"]) -> None: ...

Global___UpdateLeaseRequest: typing_extensions.TypeAlias = UpdateLeaseRequest

@typing.final
class DeleteLeaseRequest(google.protobuf.message.Message):
    """Request to delete a lease."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the lease."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

Global___DeleteLeaseRequest: typing_extensions.TypeAlias = DeleteLeaseRequest

@typing.final
class RotateTokenRequest(google.protobuf.message.Message):
    """Request to rotate the authentication token for a client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The parent resource name (namespace)."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["parent", b"parent"]) -> None: ...

Global___RotateTokenRequest: typing_extensions.TypeAlias = RotateTokenRequest

@typing.final
class RotateTokenResponse(google.protobuf.message.Message):
    """Response containing the newly rotated token."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    EXPIRY_FIELD_NUMBER: builtins.int
    token: builtins.str
    """The new authentication token."""
    @property
    def expiry(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The expiration time of the new token."""

    def __init__(
        self,
        *,
        token: builtins.str = ...,
        expiry: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["expiry", b"expiry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["expiry", b"expiry", "token", b"token"]) -> None: ...

Global___RotateTokenResponse: typing_extensions.TypeAlias = RotateTokenResponse
