name: "SA8775P ES22 AWE Firmware"
description: "ES22 AWE firmware update package (QDL)"
data:
  folder: "r00002.2a_AWE"
steps:
  - set_mode: edl
    check_dmesg: "qcserial"

  - name: "UFS Provisioning"
    retry_mode: edl
    qdl:
      storage: ufs
      programmer: prog_firehose_ddr.elf
      files:
        - provision_default.xml

  - sleep: 5

  - set_mode: edl
    check_dmesg: "qcserial"

  - name: "Flash UFS"
    retry_mode: edl
    qdl:
      storage: ufs
      programmer: prog_firehose_ddr.elf
      files:
        - "rawprogram*.xml"
        - "patch*.xml"

  - sleep: 10

  - set_mode: edl
    check_dmesg: "qcserial"

  - name: "Flash SPINOR"
    retry_mode: edl
    qdl:
      storage: spinor
      programmer: prog_firehose_ddr.elf
      files:
        - "rawprogram*.xml"

  - sleep: 30

  - set_mode: fastboot
    check_dmesg: "Product: Android"

  - name: "Flash ABL"
    fastboot:
      flash:
        - partition: abl_a
          file: sa8775p_es21_abl_signed.elf
        - partition: abl_b
          file: sa8775p_es21_abl_signed.elf

  - name: "Flash CDT"
    fastboot:
      flash:
        - partition: cdt
          file: ufs/LEMANSAU_QAM_1.1.0.bin
          revision: v1
        - partition: cdt
          file: ufs/LEMANSAU_QAM_1.1.0.bin
          revision: v2
        - partition: cdt
          file: ufs/LEMANSAU_QAM_1.2.0.bin
          revision: v3
        - partition: cdt
          file: ufs/LEMANSAU_QAM_1.2.0.bin
          revision: v4
      continue: true
