// Copyright 2024 The Jumpstarter Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jumpstarter/v1/jumpstarter.proto

package jumpstarterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Registration request sent by an exporter to the controller.
type RegisterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Labels        map[string]string       `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value metadata labels.
	Reports       []*DriverInstanceReport `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`                                                                         // Driver instance reports for this exporter.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetReports() []*DriverInstanceReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

// Report describing a single driver instance on an exporter.
type DriverInstanceReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uuid               string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                                                                                                 // Unique identifier within the exporter.
	ParentUuid         *string                `protobuf:"bytes,2,opt,name=parent_uuid,json=parentUuid,proto3,oneof" json:"parent_uuid,omitempty"`                                                                                             // Parent device UUID, if this is a child device.
	Labels             map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                                                   // Key-value metadata labels.
	Description        *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`                                                                                                             // Custom driver description for CLI display.
	MethodsDescription map[string]string      `protobuf:"bytes,5,rep,name=methods_description,json=methodsDescription,proto3" json:"methods_description,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Method name to help text mapping for CLI.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DriverInstanceReport) Reset() {
	*x = DriverInstanceReport{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverInstanceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInstanceReport) ProtoMessage() {}

func (x *DriverInstanceReport) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInstanceReport.ProtoReflect.Descriptor instead.
func (*DriverInstanceReport) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{1}
}

func (x *DriverInstanceReport) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DriverInstanceReport) GetParentUuid() string {
	if x != nil && x.ParentUuid != nil {
		return *x.ParentUuid
	}
	return ""
}

func (x *DriverInstanceReport) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DriverInstanceReport) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *DriverInstanceReport) GetMethodsDescription() map[string]string {
	if x != nil {
		return x.MethodsDescription
	}
	return nil
}

// Registration response returned by the controller.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Assigned exporter UUID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Request to unregister an exporter from the controller.
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Reason for unregistering.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Response to an unregister request.
type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{4}
}

// Request to listen for incoming client connections on a lease.
type ListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseName     string                 `protobuf:"bytes,1,opt,name=lease_name,json=leaseName,proto3" json:"lease_name,omitempty"` // Name of the lease to listen on.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{5}
}

func (x *ListenRequest) GetLeaseName() string {
	if x != nil {
		return x.LeaseName
	}
	return ""
}

// Response containing router connection details for an incoming client.
type ListenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RouterEndpoint string                 `protobuf:"bytes,1,opt,name=router_endpoint,json=routerEndpoint,proto3" json:"router_endpoint,omitempty"` // The router gRPC endpoint URL.
	RouterToken    string                 `protobuf:"bytes,2,opt,name=router_token,json=routerToken,proto3" json:"router_token,omitempty"`          // Authentication token for the router.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListenResponse) Reset() {
	*x = ListenResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse) ProtoMessage() {}

func (x *ListenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse.ProtoReflect.Descriptor instead.
func (*ListenResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{6}
}

func (x *ListenResponse) GetRouterEndpoint() string {
	if x != nil {
		return x.RouterEndpoint
	}
	return ""
}

func (x *ListenResponse) GetRouterToken() string {
	if x != nil {
		return x.RouterToken
	}
	return ""
}

// Request to subscribe to exporter lease status updates.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{7}
}

// Lease status update for an exporter.
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leased        bool                   `protobuf:"varint,1,opt,name=leased,proto3" json:"leased,omitempty"`                                                                            // Whether the exporter is currently leased.
	LeaseName     *string                `protobuf:"bytes,2,opt,name=lease_name,json=leaseName,proto3,oneof" json:"lease_name,omitempty"`                                                // Name of the active lease, if any.
	ClientName    *string                `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3,oneof" json:"client_name,omitempty"`                                             // Name of the connected client, if any.
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // User-defined lease context metadata.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetLeased() bool {
	if x != nil {
		return x.Leased
	}
	return false
}

func (x *StatusResponse) GetLeaseName() string {
	if x != nil && x.LeaseName != nil {
		return *x.LeaseName
	}
	return ""
}

func (x *StatusResponse) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

func (x *StatusResponse) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Request to dial an exporter through the router.
type DialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseName     string                 `protobuf:"bytes,1,opt,name=lease_name,json=leaseName,proto3" json:"lease_name,omitempty"` // Name of the lease to connect through.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{9}
}

func (x *DialRequest) GetLeaseName() string {
	if x != nil {
		return x.LeaseName
	}
	return ""
}

// Response containing router connection details for the dialed exporter.
type DialResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RouterEndpoint string                 `protobuf:"bytes,1,opt,name=router_endpoint,json=routerEndpoint,proto3" json:"router_endpoint,omitempty"` // The router gRPC endpoint URL.
	RouterToken    string                 `protobuf:"bytes,2,opt,name=router_token,json=routerToken,proto3" json:"router_token,omitempty"`          // Authentication token for the router.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DialResponse) Reset() {
	*x = DialResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResponse) ProtoMessage() {}

func (x *DialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResponse.ProtoReflect.Descriptor instead.
func (*DialResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{10}
}

func (x *DialResponse) GetRouterEndpoint() string {
	if x != nil {
		return x.RouterEndpoint
	}
	return ""
}

func (x *DialResponse) GetRouterToken() string {
	if x != nil {
		return x.RouterToken
	}
	return ""
}

// Request to report exporter status to the controller.
type ReportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ExporterStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=jumpstarter.v1.ExporterStatus" json:"status,omitempty"`    // Current exporter status.
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`                                // Optional human-readable status message.
	ReleaseLease  *bool                  `protobuf:"varint,3,opt,name=release_lease,json=releaseLease,proto3,oneof" json:"release_lease,omitempty"` // When true, controller should release the active lease.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{11}
}

func (x *ReportStatusRequest) GetStatus() ExporterStatus {
	if x != nil {
		return x.Status
	}
	return ExporterStatus_EXPORTER_STATUS_UNSPECIFIED
}

func (x *ReportStatusRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ReportStatusRequest) GetReleaseLease() bool {
	if x != nil && x.ReleaseLease != nil {
		return *x.ReleaseLease
	}
	return false
}

// Response to a status report request.
type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{12}
}

// Response containing the exporter driver report.
type GetReportResponse struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Uuid                 string                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                                               // Exporter UUID.
	Labels               map[string]string       `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value metadata labels.
	Reports              []*DriverInstanceReport `protobuf:"bytes,3,rep,name=reports,proto3" json:"reports,omitempty"`                                                                         // Driver instance reports.
	AlternativeEndpoints []*Endpoint             `protobuf:"bytes,4,rep,name=alternative_endpoints,json=alternativeEndpoints,proto3" json:"alternative_endpoints,omitempty"`                   // Alternative connection endpoints.
	Motd                 string                  `protobuf:"bytes,5,opt,name=motd,proto3" json:"motd,omitempty"`                                                                               // Message of the day shown to clients when entering a shell.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{13}
}

func (x *GetReportResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetReportResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GetReportResponse) GetReports() []*DriverInstanceReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *GetReportResponse) GetAlternativeEndpoints() []*Endpoint {
	if x != nil {
		return x.AlternativeEndpoints
	}
	return nil
}

func (x *GetReportResponse) GetMotd() string {
	if x != nil {
		return x.Motd
	}
	return ""
}

// Connection endpoint with TLS credentials.
type Endpoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Endpoint          string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                            // The endpoint URL.
	Certificate       string                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`                                      // Server TLS certificate.
	ClientCertificate string                 `protobuf:"bytes,3,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"` // Client TLS certificate.
	ClientPrivateKey  string                 `protobuf:"bytes,4,opt,name=client_private_key,json=clientPrivateKey,proto3" json:"client_private_key,omitempty"`  // Client TLS private key.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{14}
}

func (x *Endpoint) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Endpoint) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *Endpoint) GetClientCertificate() string {
	if x != nil {
		return x.ClientCertificate
	}
	return ""
}

func (x *Endpoint) GetClientPrivateKey() string {
	if x != nil {
		return x.ClientPrivateKey
	}
	return ""
}

// Request to invoke a method on a driver instance.
type DriverCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // UUID of the driver instance.
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // Method name to invoke.
	Args          []*structpb.Value      `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`     // Arguments for the method call.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCallRequest) Reset() {
	*x = DriverCallRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCallRequest) ProtoMessage() {}

func (x *DriverCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCallRequest.ProtoReflect.Descriptor instead.
func (*DriverCallRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{15}
}

func (x *DriverCallRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DriverCallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DriverCallRequest) GetArgs() []*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

// Response from a driver method invocation.
type DriverCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // UUID of the driver instance.
	Result        *structpb.Value        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // Return value from the method call.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCallResponse) Reset() {
	*x = DriverCallResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCallResponse) ProtoMessage() {}

func (x *DriverCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCallResponse.ProtoReflect.Descriptor instead.
func (*DriverCallResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{16}
}

func (x *DriverCallResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DriverCallResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

// Request to invoke a streaming method on a driver instance.
type StreamingDriverCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // UUID of the driver instance.
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // Method name to invoke.
	Args          []*structpb.Value      `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`     // Arguments for the method call.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingDriverCallRequest) Reset() {
	*x = StreamingDriverCallRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingDriverCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingDriverCallRequest) ProtoMessage() {}

func (x *StreamingDriverCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingDriverCallRequest.ProtoReflect.Descriptor instead.
func (*StreamingDriverCallRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{17}
}

func (x *StreamingDriverCallRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StreamingDriverCallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StreamingDriverCallRequest) GetArgs() []*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

// Response from a streaming driver method invocation.
type StreamingDriverCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // UUID of the driver instance.
	Result        *structpb.Value        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // Return value from the method call.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingDriverCallResponse) Reset() {
	*x = StreamingDriverCallResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingDriverCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingDriverCallResponse) ProtoMessage() {}

func (x *StreamingDriverCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingDriverCallResponse.ProtoReflect.Descriptor instead.
func (*StreamingDriverCallResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{18}
}

func (x *StreamingDriverCallResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StreamingDriverCallResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

// A log message from the exporter log stream.
type LogStreamResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                                                                                           // UUID of the driver instance.
	Severity         string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                                                   // Log severity level.
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                                                                     // Log message content.
	Source           *LogSource             `protobuf:"varint,4,opt,name=source,proto3,enum=jumpstarter.v1.LogSource,oneof" json:"source,omitempty"`                                                                                  // Source of the log message.
	DriverType       *string                `protobuf:"bytes,5,opt,name=driver_type,json=driverType,proto3,oneof" json:"driver_type,omitempty"`                                                                                       // Driver category when source=DRIVER (e.g. "power", "storage").
	Operation        *string                `protobuf:"bytes,6,opt,name=operation,proto3,oneof" json:"operation,omitempty"`                                                                                                           // Operation name when the log is part of a known operation.
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`                                                                                                           // Explicit timestamp of the log entry.
	StructuredFields map[string]string      `protobuf:"bytes,8,rep,name=structured_fields,json=structuredFields,proto3" json:"structured_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional structured key-value fields.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{19}
}

func (x *LogStreamResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LogStreamResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogStreamResponse) GetSource() LogSource {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return LogSource_LOG_SOURCE_UNSPECIFIED
}

func (x *LogStreamResponse) GetDriverType() string {
	if x != nil && x.DriverType != nil {
		return *x.DriverType
	}
	return ""
}

func (x *LogStreamResponse) GetOperation() string {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return ""
}

func (x *LogStreamResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogStreamResponse) GetStructuredFields() map[string]string {
	if x != nil {
		return x.StructuredFields
	}
	return nil
}

// Request to reset the exporter connection.
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{20}
}

// Response to a reset request.
type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{21}
}

// Request to retrieve a lease by name.
type GetLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the lease to retrieve.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseRequest) Reset() {
	*x = GetLeaseRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseRequest) ProtoMessage() {}

func (x *GetLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseRequest.ProtoReflect.Descriptor instead.
func (*GetLeaseRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{22}
}

func (x *GetLeaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response containing lease details.
type GetLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`                                   // Requested lease duration.
	Selector      *LabelSelector         `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`                                   // Label selector for matching exporters.
	BeginTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=begin_time,json=beginTime,proto3,oneof" json:"begin_time,omitempty"`          // Lease start time, if active.
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`                // Lease end time, if active.
	ExporterUuid  *string                `protobuf:"bytes,5,opt,name=exporter_uuid,json=exporterUuid,proto3,oneof" json:"exporter_uuid,omitempty"` // UUID of the assigned exporter, if any.
	Conditions    []*Condition           `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`                               // Lease status conditions.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseResponse) Reset() {
	*x = GetLeaseResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseResponse) ProtoMessage() {}

func (x *GetLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseResponse.ProtoReflect.Descriptor instead.
func (*GetLeaseResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{23}
}

func (x *GetLeaseResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *GetLeaseResponse) GetSelector() *LabelSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *GetLeaseResponse) GetBeginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BeginTime
	}
	return nil
}

func (x *GetLeaseResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetLeaseResponse) GetExporterUuid() string {
	if x != nil && x.ExporterUuid != nil {
		return *x.ExporterUuid
	}
	return ""
}

func (x *GetLeaseResponse) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// Request to create a new lease for an exporter.
type RequestLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"` // Desired lease duration.
	Selector      *LabelSelector         `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"` // Label selector for matching exporters.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLeaseRequest) Reset() {
	*x = RequestLeaseRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLeaseRequest) ProtoMessage() {}

func (x *RequestLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLeaseRequest.ProtoReflect.Descriptor instead.
func (*RequestLeaseRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{24}
}

func (x *RequestLeaseRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *RequestLeaseRequest) GetSelector() *LabelSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

// Response containing the name of the created lease.
type RequestLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the created lease.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLeaseResponse) Reset() {
	*x = RequestLeaseResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLeaseResponse) ProtoMessage() {}

func (x *RequestLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLeaseResponse.ProtoReflect.Descriptor instead.
func (*RequestLeaseResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{25}
}

func (x *RequestLeaseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to release an active lease.
type ReleaseLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the lease to release.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseRequest) Reset() {
	*x = ReleaseLeaseRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseRequest) ProtoMessage() {}

func (x *ReleaseLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{26}
}

func (x *ReleaseLeaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response to a release lease request.
type ReleaseLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseResponse) Reset() {
	*x = ReleaseLeaseResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseResponse) ProtoMessage() {}

func (x *ReleaseLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{27}
}

// Request to list all leases.
type ListLeasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesRequest) Reset() {
	*x = ListLeasesRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesRequest) ProtoMessage() {}

func (x *ListLeasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesRequest.ProtoReflect.Descriptor instead.
func (*ListLeasesRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{28}
}

// Response containing the list of lease names.
type ListLeasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"` // Names of all leases.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesResponse) Reset() {
	*x = ListLeasesResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesResponse) ProtoMessage() {}

func (x *ListLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListLeasesResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{29}
}

func (x *ListLeasesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// Request to retrieve the current exporter status.
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{30}
}

// Response containing the current exporter status.
type GetStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         ExporterStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=jumpstarter.v1.ExporterStatus" json:"status,omitempty"`                                             // Current exporter status.
	Message        *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`                                                                         // Human-readable status message.
	StatusVersion  uint64                 `protobuf:"varint,3,opt,name=status_version,json=statusVersion,proto3" json:"status_version,omitempty"`                                             // Monotonic counter, increments on each status change.
	PreviousStatus *ExporterStatus        `protobuf:"varint,4,opt,name=previous_status,json=previousStatus,proto3,enum=jumpstarter.v1.ExporterStatus,oneof" json:"previous_status,omitempty"` // Previous status for transition tracking.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{31}
}

func (x *GetStatusResponse) GetStatus() ExporterStatus {
	if x != nil {
		return x.Status
	}
	return ExporterStatus_EXPORTER_STATUS_UNSPECIFIED
}

func (x *GetStatusResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *GetStatusResponse) GetStatusVersion() uint64 {
	if x != nil {
		return x.StatusVersion
	}
	return 0
}

func (x *GetStatusResponse) GetPreviousStatus() ExporterStatus {
	if x != nil && x.PreviousStatus != nil {
		return *x.PreviousStatus
	}
	return ExporterStatus_EXPORTER_STATUS_UNSPECIFIED
}

// Request to end the current exporter session.
type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{32}
}

// Response to an end session request.
type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`      // Whether the session ended successfully.
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"` // Human-readable result message.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{33}
}

func (x *EndSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EndSessionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Request to discover optional service endpoints.
type GetServiceEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceEndpointsRequest) Reset() {
	*x = GetServiceEndpointsRequest{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceEndpointsRequest) ProtoMessage() {}

func (x *GetServiceEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceEndpointsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{34}
}

// Response containing optional service endpoint addresses.
type GetServiceEndpointsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty when no optional services (e.g. telemetry) are deployed.
	TelemetryEndpoints []*TelemetryEndpoint `protobuf:"bytes,1,rep,name=telemetry_endpoints,json=telemetryEndpoints,proto3" json:"telemetry_endpoints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetServiceEndpointsResponse) Reset() {
	*x = GetServiceEndpointsResponse{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceEndpointsResponse) ProtoMessage() {}

func (x *GetServiceEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceEndpointsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{35}
}

func (x *GetServiceEndpointsResponse) GetTelemetryEndpoints() []*TelemetryEndpoint {
	if x != nil {
		return x.TelemetryEndpoints
	}
	return nil
}

// Address of an optional telemetry service endpoint.
type TelemetryEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                          // gRPC address (host:port).
	Certificate   string                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`                    // Optional CA certificate PEM for TLS verification.
	MinSeverity   string                 `protobuf:"bytes,3,opt,name=min_severity,json=minSeverity,proto3" json:"min_severity,omitempty"` // Minimum log severity to forward (e.g. "info", "warning").
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEndpoint) Reset() {
	*x = TelemetryEndpoint{}
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEndpoint) ProtoMessage() {}

func (x *TelemetryEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_jumpstarter_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEndpoint.ProtoReflect.Descriptor instead.
func (*TelemetryEndpoint) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP(), []int{36}
}

func (x *TelemetryEndpoint) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *TelemetryEndpoint) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *TelemetryEndpoint) GetMinSeverity() string {
	if x != nil {
		return x.MinSeverity
	}
	return ""
}

var File_jumpstarter_v1_jumpstarter_proto protoreflect.FileDescriptor

const file_jumpstarter_v1_jumpstarter_proto_rawDesc = "" +
	"\n" +
	" jumpstarter/v1/jumpstarter.proto\x12\x0ejumpstarter.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fjumpstarter/v1/kubernetes.proto\x1a\x1bjumpstarter/v1/common.proto\"\xd1\x01\n" +
	"\x0fRegisterRequest\x12C\n" +
	"\x06labels\x18\x01 \x03(\v2+.jumpstarter.v1.RegisterRequest.LabelsEntryR\x06labels\x12>\n" +
	"\areports\x18\x02 \x03(\v2$.jumpstarter.v1.DriverInstanceReportR\areports\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x03\n" +
	"\x14DriverInstanceReport\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12$\n" +
	"\vparent_uuid\x18\x02 \x01(\tH\x00R\n" +
	"parentUuid\x88\x01\x01\x12H\n" +
	"\x06labels\x18\x03 \x03(\v20.jumpstarter.v1.DriverInstanceReport.LabelsEntryR\x06labels\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12m\n" +
	"\x13methods_description\x18\x05 \x03(\v2<.jumpstarter.v1.DriverInstanceReport.MethodsDescriptionEntryR\x12methodsDescription\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17MethodsDescriptionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_parent_uuidB\x0e\n" +
	"\f_description\"&\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"+\n" +
	"\x11UnregisterRequest\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x14\n" +
	"\x12UnregisterResponse\".\n" +
	"\rListenRequest\x12\x1d\n" +
	"\n" +
	"lease_name\x18\x01 \x01(\tR\tleaseName\"\\\n" +
	"\x0eListenResponse\x12'\n" +
	"\x0frouter_endpoint\x18\x01 \x01(\tR\x0erouterEndpoint\x12!\n" +
	"\frouter_token\x18\x02 \x01(\tR\vrouterToken\"\x0f\n" +
	"\rStatusRequest\"\x94\x02\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06leased\x18\x01 \x01(\bR\x06leased\x12\"\n" +
	"\n" +
	"lease_name\x18\x02 \x01(\tH\x00R\tleaseName\x88\x01\x01\x12$\n" +
	"\vclient_name\x18\x03 \x01(\tH\x01R\n" +
	"clientName\x88\x01\x01\x12E\n" +
	"\acontext\x18\x04 \x03(\v2+.jumpstarter.v1.StatusResponse.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_lease_nameB\x0e\n" +
	"\f_client_name\",\n" +
	"\vDialRequest\x12\x1d\n" +
	"\n" +
	"lease_name\x18\x01 \x01(\tR\tleaseName\"Z\n" +
	"\fDialResponse\x12'\n" +
	"\x0frouter_endpoint\x18\x01 \x01(\tR\x0erouterEndpoint\x12!\n" +
	"\frouter_token\x18\x02 \x01(\tR\vrouterToken\"\xb4\x01\n" +
	"\x13ReportStatusRequest\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.jumpstarter.v1.ExporterStatusR\x06status\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12(\n" +
	"\rrelease_lease\x18\x03 \x01(\bH\x01R\freleaseLease\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\x10\n" +
	"\x0e_release_lease\"\x16\n" +
	"\x14ReportStatusResponse\"\xcc\x02\n" +
	"\x11GetReportResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12E\n" +
	"\x06labels\x18\x02 \x03(\v2-.jumpstarter.v1.GetReportResponse.LabelsEntryR\x06labels\x12>\n" +
	"\areports\x18\x03 \x03(\v2$.jumpstarter.v1.DriverInstanceReportR\areports\x12M\n" +
	"\x15alternative_endpoints\x18\x04 \x03(\v2\x18.jumpstarter.v1.EndpointR\x14alternativeEndpoints\x12\x12\n" +
	"\x04motd\x18\x05 \x01(\tR\x04motd\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\bEndpoint\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12 \n" +
	"\vcertificate\x18\x02 \x01(\tR\vcertificate\x12-\n" +
	"\x12client_certificate\x18\x03 \x01(\tR\x11clientCertificate\x12,\n" +
	"\x12client_private_key\x18\x04 \x01(\tR\x10clientPrivateKey\"k\n" +
	"\x11DriverCallRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12*\n" +
	"\x04args\x18\x03 \x03(\v2\x16.google.protobuf.ValueR\x04args\"X\n" +
	"\x12DriverCallResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x06result\"t\n" +
	"\x1aStreamingDriverCallRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12*\n" +
	"\x04args\x18\x03 \x03(\v2\x16.google.protobuf.ValueR\x04args\"a\n" +
	"\x1bStreamingDriverCallResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x06result\"\xff\x03\n" +
	"\x11LogStreamResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x126\n" +
	"\x06source\x18\x04 \x01(\x0e2\x19.jumpstarter.v1.LogSourceH\x00R\x06source\x88\x01\x01\x12$\n" +
	"\vdriver_type\x18\x05 \x01(\tH\x01R\n" +
	"driverType\x88\x01\x01\x12!\n" +
	"\toperation\x18\x06 \x01(\tH\x02R\toperation\x88\x01\x01\x12=\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\ttimestamp\x88\x01\x01\x12d\n" +
	"\x11structured_fields\x18\b \x03(\v27.jumpstarter.v1.LogStreamResponse.StructuredFieldsEntryR\x10structuredFields\x1aC\n" +
	"\x15StructuredFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_sourceB\x0e\n" +
	"\f_driver_typeB\f\n" +
	"\n" +
	"_operationB\f\n" +
	"\n" +
	"_timestamp\"\x0e\n" +
	"\fResetRequest\"\x0f\n" +
	"\rResetResponse\"%\n" +
	"\x0fGetLeaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x93\x03\n" +
	"\x10GetLeaseResponse\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\x129\n" +
	"\bselector\x18\x02 \x01(\v2\x1d.jumpstarter.v1.LabelSelectorR\bselector\x12>\n" +
	"\n" +
	"begin_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tbeginTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01\x12(\n" +
	"\rexporter_uuid\x18\x05 \x01(\tH\x02R\fexporterUuid\x88\x01\x01\x129\n" +
	"\n" +
	"conditions\x18\x06 \x03(\v2\x19.jumpstarter.v1.ConditionR\n" +
	"conditionsB\r\n" +
	"\v_begin_timeB\v\n" +
	"\t_end_timeB\x10\n" +
	"\x0e_exporter_uuid\"\x87\x01\n" +
	"\x13RequestLeaseRequest\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\x129\n" +
	"\bselector\x18\x02 \x01(\v2\x1d.jumpstarter.v1.LabelSelectorR\bselector\"*\n" +
	"\x14RequestLeaseResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13ReleaseLeaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14ReleaseLeaseResponse\"\x13\n" +
	"\x11ListLeasesRequest\"*\n" +
	"\x12ListLeasesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\x12\n" +
	"\x10GetStatusRequest\"\xff\x01\n" +
	"\x11GetStatusResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.jumpstarter.v1.ExporterStatusR\x06status\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12%\n" +
	"\x0estatus_version\x18\x03 \x01(\x04R\rstatusVersion\x12L\n" +
	"\x0fprevious_status\x18\x04 \x01(\x0e2\x1e.jumpstarter.v1.ExporterStatusH\x01R\x0epreviousStatus\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\x12\n" +
	"\x10_previous_status\"\x13\n" +
	"\x11EndSessionRequest\"Y\n" +
	"\x12EndSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\x1c\n" +
	"\x1aGetServiceEndpointsRequest\"q\n" +
	"\x1bGetServiceEndpointsResponse\x12R\n" +
	"\x13telemetry_endpoints\x18\x01 \x03(\v2!.jumpstarter.v1.TelemetryEndpointR\x12telemetryEndpoints\"t\n" +
	"\x11TelemetryEndpoint\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12 \n" +
	"\vcertificate\x18\x02 \x01(\tR\vcertificate\x12!\n" +
	"\fmin_severity\x18\x03 \x01(\tR\vminSeverity2\xb5\a\n" +
	"\x11ControllerService\x12M\n" +
	"\bRegister\x12\x1f.jumpstarter.v1.RegisterRequest\x1a .jumpstarter.v1.RegisterResponse\x12S\n" +
	"\n" +
	"Unregister\x12!.jumpstarter.v1.UnregisterRequest\x1a\".jumpstarter.v1.UnregisterResponse\x12Y\n" +
	"\fReportStatus\x12#.jumpstarter.v1.ReportStatusRequest\x1a$.jumpstarter.v1.ReportStatusResponse\x12I\n" +
	"\x06Listen\x12\x1d.jumpstarter.v1.ListenRequest\x1a\x1e.jumpstarter.v1.ListenResponse0\x01\x12I\n" +
	"\x06Status\x12\x1d.jumpstarter.v1.StatusRequest\x1a\x1e.jumpstarter.v1.StatusResponse0\x01\x12A\n" +
	"\x04Dial\x12\x1b.jumpstarter.v1.DialRequest\x1a\x1c.jumpstarter.v1.DialResponse\x12M\n" +
	"\bGetLease\x12\x1f.jumpstarter.v1.GetLeaseRequest\x1a .jumpstarter.v1.GetLeaseResponse\x12Y\n" +
	"\fRequestLease\x12#.jumpstarter.v1.RequestLeaseRequest\x1a$.jumpstarter.v1.RequestLeaseResponse\x12Y\n" +
	"\fReleaseLease\x12#.jumpstarter.v1.ReleaseLeaseRequest\x1a$.jumpstarter.v1.ReleaseLeaseResponse\x12S\n" +
	"\n" +
	"ListLeases\x12!.jumpstarter.v1.ListLeasesRequest\x1a\".jumpstarter.v1.ListLeasesResponse\x12n\n" +
	"\x13GetServiceEndpoints\x12*.jumpstarter.v1.GetServiceEndpointsRequest\x1a+.jumpstarter.v1.GetServiceEndpointsResponse2\xd7\x04\n" +
	"\x0fExporterService\x12F\n" +
	"\tGetReport\x12\x16.google.protobuf.Empty\x1a!.jumpstarter.v1.GetReportResponse\x12S\n" +
	"\n" +
	"DriverCall\x12!.jumpstarter.v1.DriverCallRequest\x1a\".jumpstarter.v1.DriverCallResponse\x12p\n" +
	"\x13StreamingDriverCall\x12*.jumpstarter.v1.StreamingDriverCallRequest\x1a+.jumpstarter.v1.StreamingDriverCallResponse0\x01\x12H\n" +
	"\tLogStream\x12\x16.google.protobuf.Empty\x1a!.jumpstarter.v1.LogStreamResponse0\x01\x12D\n" +
	"\x05Reset\x12\x1c.jumpstarter.v1.ResetRequest\x1a\x1d.jumpstarter.v1.ResetResponse\x12P\n" +
	"\tGetStatus\x12 .jumpstarter.v1.GetStatusRequest\x1a!.jumpstarter.v1.GetStatusResponse\x12S\n" +
	"\n" +
	"EndSession\x12!.jumpstarter.v1.EndSessionRequest\x1a\".jumpstarter.v1.EndSessionResponseB\xe1\x01\n" +
	"\x12com.jumpstarter.v1B\x10JumpstarterProtoP\x01Z`github.com/jumpstarter-dev/jumpstarter/controller/internal/protocol/jumpstarter/v1;jumpstarterv1\xa2\x02\x03JXX\xaa\x02\x0eJumpstarter.V1\xca\x02\x0eJumpstarter\\V1\xe2\x02\x1aJumpstarter\\V1\\GPBMetadata\xea\x02\x0fJumpstarter::V1b\x06proto3"

var (
	file_jumpstarter_v1_jumpstarter_proto_rawDescOnce sync.Once
	file_jumpstarter_v1_jumpstarter_proto_rawDescData []byte
)

func file_jumpstarter_v1_jumpstarter_proto_rawDescGZIP() []byte {
	file_jumpstarter_v1_jumpstarter_proto_rawDescOnce.Do(func() {
		file_jumpstarter_v1_jumpstarter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_jumpstarter_proto_rawDesc), len(file_jumpstarter_v1_jumpstarter_proto_rawDesc)))
	})
	return file_jumpstarter_v1_jumpstarter_proto_rawDescData
}

var file_jumpstarter_v1_jumpstarter_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_jumpstarter_v1_jumpstarter_proto_goTypes = []any{
	(*RegisterRequest)(nil),             // 0: jumpstarter.v1.RegisterRequest
	(*DriverInstanceReport)(nil),        // 1: jumpstarter.v1.DriverInstanceReport
	(*RegisterResponse)(nil),            // 2: jumpstarter.v1.RegisterResponse
	(*UnregisterRequest)(nil),           // 3: jumpstarter.v1.UnregisterRequest
	(*UnregisterResponse)(nil),          // 4: jumpstarter.v1.UnregisterResponse
	(*ListenRequest)(nil),               // 5: jumpstarter.v1.ListenRequest
	(*ListenResponse)(nil),              // 6: jumpstarter.v1.ListenResponse
	(*StatusRequest)(nil),               // 7: jumpstarter.v1.StatusRequest
	(*StatusResponse)(nil),              // 8: jumpstarter.v1.StatusResponse
	(*DialRequest)(nil),                 // 9: jumpstarter.v1.DialRequest
	(*DialResponse)(nil),                // 10: jumpstarter.v1.DialResponse
	(*ReportStatusRequest)(nil),         // 11: jumpstarter.v1.ReportStatusRequest
	(*ReportStatusResponse)(nil),        // 12: jumpstarter.v1.ReportStatusResponse
	(*GetReportResponse)(nil),           // 13: jumpstarter.v1.GetReportResponse
	(*Endpoint)(nil),                    // 14: jumpstarter.v1.Endpoint
	(*DriverCallRequest)(nil),           // 15: jumpstarter.v1.DriverCallRequest
	(*DriverCallResponse)(nil),          // 16: jumpstarter.v1.DriverCallResponse
	(*StreamingDriverCallRequest)(nil),  // 17: jumpstarter.v1.StreamingDriverCallRequest
	(*StreamingDriverCallResponse)(nil), // 18: jumpstarter.v1.StreamingDriverCallResponse
	(*LogStreamResponse)(nil),           // 19: jumpstarter.v1.LogStreamResponse
	(*ResetRequest)(nil),                // 20: jumpstarter.v1.ResetRequest
	(*ResetResponse)(nil),               // 21: jumpstarter.v1.ResetResponse
	(*GetLeaseRequest)(nil),             // 22: jumpstarter.v1.GetLeaseRequest
	(*GetLeaseResponse)(nil),            // 23: jumpstarter.v1.GetLeaseResponse
	(*RequestLeaseRequest)(nil),         // 24: jumpstarter.v1.RequestLeaseRequest
	(*RequestLeaseResponse)(nil),        // 25: jumpstarter.v1.RequestLeaseResponse
	(*ReleaseLeaseRequest)(nil),         // 26: jumpstarter.v1.ReleaseLeaseRequest
	(*ReleaseLeaseResponse)(nil),        // 27: jumpstarter.v1.ReleaseLeaseResponse
	(*ListLeasesRequest)(nil),           // 28: jumpstarter.v1.ListLeasesRequest
	(*ListLeasesResponse)(nil),          // 29: jumpstarter.v1.ListLeasesResponse
	(*GetStatusRequest)(nil),            // 30: jumpstarter.v1.GetStatusRequest
	(*GetStatusResponse)(nil),           // 31: jumpstarter.v1.GetStatusResponse
	(*EndSessionRequest)(nil),           // 32: jumpstarter.v1.EndSessionRequest
	(*EndSessionResponse)(nil),          // 33: jumpstarter.v1.EndSessionResponse
	(*GetServiceEndpointsRequest)(nil),  // 34: jumpstarter.v1.GetServiceEndpointsRequest
	(*GetServiceEndpointsResponse)(nil), // 35: jumpstarter.v1.GetServiceEndpointsResponse
	(*TelemetryEndpoint)(nil),           // 36: jumpstarter.v1.TelemetryEndpoint
	nil,                                 // 37: jumpstarter.v1.RegisterRequest.LabelsEntry
	nil,                                 // 38: jumpstarter.v1.DriverInstanceReport.LabelsEntry
	nil,                                 // 39: jumpstarter.v1.DriverInstanceReport.MethodsDescriptionEntry
	nil,                                 // 40: jumpstarter.v1.StatusResponse.ContextEntry
	nil,                                 // 41: jumpstarter.v1.GetReportResponse.LabelsEntry
	nil,                                 // 42: jumpstarter.v1.LogStreamResponse.StructuredFieldsEntry
	(ExporterStatus)(0),                 // 43: jumpstarter.v1.ExporterStatus
	(*structpb.Value)(nil),              // 44: google.protobuf.Value
	(LogSource)(0),                      // 45: jumpstarter.v1.LogSource
	(*timestamppb.Timestamp)(nil),       // 46: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 47: google.protobuf.Duration
	(*LabelSelector)(nil),               // 48: jumpstarter.v1.LabelSelector
	(*Condition)(nil),                   // 49: jumpstarter.v1.Condition
	(*emptypb.Empty)(nil),               // 50: google.protobuf.Empty
}
var file_jumpstarter_v1_jumpstarter_proto_depIdxs = []int32{
	37, // 0: jumpstarter.v1.RegisterRequest.labels:type_name -> jumpstarter.v1.RegisterRequest.LabelsEntry
	1,  // 1: jumpstarter.v1.RegisterRequest.reports:type_name -> jumpstarter.v1.DriverInstanceReport
	38, // 2: jumpstarter.v1.DriverInstanceReport.labels:type_name -> jumpstarter.v1.DriverInstanceReport.LabelsEntry
	39, // 3: jumpstarter.v1.DriverInstanceReport.methods_description:type_name -> jumpstarter.v1.DriverInstanceReport.MethodsDescriptionEntry
	40, // 4: jumpstarter.v1.StatusResponse.context:type_name -> jumpstarter.v1.StatusResponse.ContextEntry
	43, // 5: jumpstarter.v1.ReportStatusRequest.status:type_name -> jumpstarter.v1.ExporterStatus
	41, // 6: jumpstarter.v1.GetReportResponse.labels:type_name -> jumpstarter.v1.GetReportResponse.LabelsEntry
	1,  // 7: jumpstarter.v1.GetReportResponse.reports:type_name -> jumpstarter.v1.DriverInstanceReport
	14, // 8: jumpstarter.v1.GetReportResponse.alternative_endpoints:type_name -> jumpstarter.v1.Endpoint
	44, // 9: jumpstarter.v1.DriverCallRequest.args:type_name -> google.protobuf.Value
	44, // 10: jumpstarter.v1.DriverCallResponse.result:type_name -> google.protobuf.Value
	44, // 11: jumpstarter.v1.StreamingDriverCallRequest.args:type_name -> google.protobuf.Value
	44, // 12: jumpstarter.v1.StreamingDriverCallResponse.result:type_name -> google.protobuf.Value
	45, // 13: jumpstarter.v1.LogStreamResponse.source:type_name -> jumpstarter.v1.LogSource
	46, // 14: jumpstarter.v1.LogStreamResponse.timestamp:type_name -> google.protobuf.Timestamp
	42, // 15: jumpstarter.v1.LogStreamResponse.structured_fields:type_name -> jumpstarter.v1.LogStreamResponse.StructuredFieldsEntry
	47, // 16: jumpstarter.v1.GetLeaseResponse.duration:type_name -> google.protobuf.Duration
	48, // 17: jumpstarter.v1.GetLeaseResponse.selector:type_name -> jumpstarter.v1.LabelSelector
	46, // 18: jumpstarter.v1.GetLeaseResponse.begin_time:type_name -> google.protobuf.Timestamp
	46, // 19: jumpstarter.v1.GetLeaseResponse.end_time:type_name -> google.protobuf.Timestamp
	49, // 20: jumpstarter.v1.GetLeaseResponse.conditions:type_name -> jumpstarter.v1.Condition
	47, // 21: jumpstarter.v1.RequestLeaseRequest.duration:type_name -> google.protobuf.Duration
	48, // 22: jumpstarter.v1.RequestLeaseRequest.selector:type_name -> jumpstarter.v1.LabelSelector
	43, // 23: jumpstarter.v1.GetStatusResponse.status:type_name -> jumpstarter.v1.ExporterStatus
	43, // 24: jumpstarter.v1.GetStatusResponse.previous_status:type_name -> jumpstarter.v1.ExporterStatus
	36, // 25: jumpstarter.v1.GetServiceEndpointsResponse.telemetry_endpoints:type_name -> jumpstarter.v1.TelemetryEndpoint
	0,  // 26: jumpstarter.v1.ControllerService.Register:input_type -> jumpstarter.v1.RegisterRequest
	3,  // 27: jumpstarter.v1.ControllerService.Unregister:input_type -> jumpstarter.v1.UnregisterRequest
	11, // 28: jumpstarter.v1.ControllerService.ReportStatus:input_type -> jumpstarter.v1.ReportStatusRequest
	5,  // 29: jumpstarter.v1.ControllerService.Listen:input_type -> jumpstarter.v1.ListenRequest
	7,  // 30: jumpstarter.v1.ControllerService.Status:input_type -> jumpstarter.v1.StatusRequest
	9,  // 31: jumpstarter.v1.ControllerService.Dial:input_type -> jumpstarter.v1.DialRequest
	22, // 32: jumpstarter.v1.ControllerService.GetLease:input_type -> jumpstarter.v1.GetLeaseRequest
	24, // 33: jumpstarter.v1.ControllerService.RequestLease:input_type -> jumpstarter.v1.RequestLeaseRequest
	26, // 34: jumpstarter.v1.ControllerService.ReleaseLease:input_type -> jumpstarter.v1.ReleaseLeaseRequest
	28, // 35: jumpstarter.v1.ControllerService.ListLeases:input_type -> jumpstarter.v1.ListLeasesRequest
	34, // 36: jumpstarter.v1.ControllerService.GetServiceEndpoints:input_type -> jumpstarter.v1.GetServiceEndpointsRequest
	50, // 37: jumpstarter.v1.ExporterService.GetReport:input_type -> google.protobuf.Empty
	15, // 38: jumpstarter.v1.ExporterService.DriverCall:input_type -> jumpstarter.v1.DriverCallRequest
	17, // 39: jumpstarter.v1.ExporterService.StreamingDriverCall:input_type -> jumpstarter.v1.StreamingDriverCallRequest
	50, // 40: jumpstarter.v1.ExporterService.LogStream:input_type -> google.protobuf.Empty
	20, // 41: jumpstarter.v1.ExporterService.Reset:input_type -> jumpstarter.v1.ResetRequest
	30, // 42: jumpstarter.v1.ExporterService.GetStatus:input_type -> jumpstarter.v1.GetStatusRequest
	32, // 43: jumpstarter.v1.ExporterService.EndSession:input_type -> jumpstarter.v1.EndSessionRequest
	2,  // 44: jumpstarter.v1.ControllerService.Register:output_type -> jumpstarter.v1.RegisterResponse
	4,  // 45: jumpstarter.v1.ControllerService.Unregister:output_type -> jumpstarter.v1.UnregisterResponse
	12, // 46: jumpstarter.v1.ControllerService.ReportStatus:output_type -> jumpstarter.v1.ReportStatusResponse
	6,  // 47: jumpstarter.v1.ControllerService.Listen:output_type -> jumpstarter.v1.ListenResponse
	8,  // 48: jumpstarter.v1.ControllerService.Status:output_type -> jumpstarter.v1.StatusResponse
	10, // 49: jumpstarter.v1.ControllerService.Dial:output_type -> jumpstarter.v1.DialResponse
	23, // 50: jumpstarter.v1.ControllerService.GetLease:output_type -> jumpstarter.v1.GetLeaseResponse
	25, // 51: jumpstarter.v1.ControllerService.RequestLease:output_type -> jumpstarter.v1.RequestLeaseResponse
	27, // 52: jumpstarter.v1.ControllerService.ReleaseLease:output_type -> jumpstarter.v1.ReleaseLeaseResponse
	29, // 53: jumpstarter.v1.ControllerService.ListLeases:output_type -> jumpstarter.v1.ListLeasesResponse
	35, // 54: jumpstarter.v1.ControllerService.GetServiceEndpoints:output_type -> jumpstarter.v1.GetServiceEndpointsResponse
	13, // 55: jumpstarter.v1.ExporterService.GetReport:output_type -> jumpstarter.v1.GetReportResponse
	16, // 56: jumpstarter.v1.ExporterService.DriverCall:output_type -> jumpstarter.v1.DriverCallResponse
	18, // 57: jumpstarter.v1.ExporterService.StreamingDriverCall:output_type -> jumpstarter.v1.StreamingDriverCallResponse
	19, // 58: jumpstarter.v1.ExporterService.LogStream:output_type -> jumpstarter.v1.LogStreamResponse
	21, // 59: jumpstarter.v1.ExporterService.Reset:output_type -> jumpstarter.v1.ResetResponse
	31, // 60: jumpstarter.v1.ExporterService.GetStatus:output_type -> jumpstarter.v1.GetStatusResponse
	33, // 61: jumpstarter.v1.ExporterService.EndSession:output_type -> jumpstarter.v1.EndSessionResponse
	44, // [44:62] is the sub-list for method output_type
	26, // [26:44] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_jumpstarter_v1_jumpstarter_proto_init() }
func file_jumpstarter_v1_jumpstarter_proto_init() {
	if File_jumpstarter_v1_jumpstarter_proto != nil {
		return
	}
	file_jumpstarter_v1_kubernetes_proto_init()
	file_jumpstarter_v1_common_proto_init()
	file_jumpstarter_v1_jumpstarter_proto_msgTypes[1].OneofWrappers = []any{}
	file_jumpstarter_v1_jumpstarter_proto_msgTypes[8].OneofWrappers = []any{}
	file_jumpstarter_v1_jumpstarter_proto_msgTypes[11].OneofWrappers = []any{}
	file_jumpstarter_v1_jumpstarter_proto_msgTypes[19].OneofWrappers = []any{}
	file_jumpstarter_v1_jumpstarter_proto_msgTypes[23].OneofWrappers = []any{}
	file_jumpstarter_v1_jumpstarter_proto_msgTypes[31].OneofWrappers = []any{}
	file_jumpstarter_v1_jumpstarter_proto_msgTypes[33].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_jumpstarter_proto_rawDesc), len(file_jumpstarter_v1_jumpstarter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_jumpstarter_v1_jumpstarter_proto_goTypes,
		DependencyIndexes: file_jumpstarter_v1_jumpstarter_proto_depIdxs,
		MessageInfos:      file_jumpstarter_v1_jumpstarter_proto_msgTypes,
	}.Build()
	File_jumpstarter_v1_jumpstarter_proto = out.File
	file_jumpstarter_v1_jumpstarter_proto_goTypes = nil
	file_jumpstarter_v1_jumpstarter_proto_depIdxs = nil
}
