// Copyright 2026 The Jumpstarter Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: jumpstarter/v1/telemetry.proto

package jumpstarterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Prometheus metric type for a MetricsFamily.
type MetricsType int32

const (
	MetricsType_METRICS_TYPE_UNSPECIFIED MetricsType = 0 // Unknown or unset type.
	MetricsType_METRICS_TYPE_COUNTER     MetricsType = 1 // Monotonic counter.
	MetricsType_METRICS_TYPE_GAUGE       MetricsType = 2 // Gauge.
	MetricsType_METRICS_TYPE_HISTOGRAM   MetricsType = 3 // Histogram (bucket / sum / count samples).
	MetricsType_METRICS_TYPE_SUMMARY     MetricsType = 4 // Summary.
	MetricsType_METRICS_TYPE_UNTYPED     MetricsType = 5 // Untyped / unknown.
)

// Enum value maps for MetricsType.
var (
	MetricsType_name = map[int32]string{
		0: "METRICS_TYPE_UNSPECIFIED",
		1: "METRICS_TYPE_COUNTER",
		2: "METRICS_TYPE_GAUGE",
		3: "METRICS_TYPE_HISTOGRAM",
		4: "METRICS_TYPE_SUMMARY",
		5: "METRICS_TYPE_UNTYPED",
	}
	MetricsType_value = map[string]int32{
		"METRICS_TYPE_UNSPECIFIED": 0,
		"METRICS_TYPE_COUNTER":     1,
		"METRICS_TYPE_GAUGE":       2,
		"METRICS_TYPE_HISTOGRAM":   3,
		"METRICS_TYPE_SUMMARY":     4,
		"METRICS_TYPE_UNTYPED":     5,
	}
)

func (x MetricsType) Enum() *MetricsType {
	p := new(MetricsType)
	*p = x
	return p
}

func (x MetricsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsType) Descriptor() protoreflect.EnumDescriptor {
	return file_jumpstarter_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (MetricsType) Type() protoreflect.EnumType {
	return &file_jumpstarter_v1_telemetry_proto_enumTypes[0]
}

func (x MetricsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsType.Descriptor instead.
func (MetricsType) EnumDescriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// Exporter → Telemetry
type MetricsStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MetricsStreamRequest_Register
	//	*MetricsStreamRequest_ScrapeResponse
	Msg           isMetricsStreamRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsStreamRequest) Reset() {
	*x = MetricsStreamRequest{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsStreamRequest) ProtoMessage() {}

func (x *MetricsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsStreamRequest.ProtoReflect.Descriptor instead.
func (*MetricsStreamRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsStreamRequest) GetMsg() isMetricsStreamRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MetricsStreamRequest) GetRegister() *MetricsRegister {
	if x != nil {
		if x, ok := x.Msg.(*MetricsStreamRequest_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *MetricsStreamRequest) GetScrapeResponse() *MetricsScrapeResponse {
	if x != nil {
		if x, ok := x.Msg.(*MetricsStreamRequest_ScrapeResponse); ok {
			return x.ScrapeResponse
		}
	}
	return nil
}

type isMetricsStreamRequest_Msg interface {
	isMetricsStreamRequest_Msg()
}

type MetricsStreamRequest_Register struct {
	Register *MetricsRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // First message: identify this exporter.
}

type MetricsStreamRequest_ScrapeResponse struct {
	ScrapeResponse *MetricsScrapeResponse `protobuf:"bytes,2,opt,name=scrape_response,json=scrapeResponse,proto3,oneof"` // Subsequent: reply to a scrape.
}

func (*MetricsStreamRequest_Register) isMetricsStreamRequest_Msg() {}

func (*MetricsStreamRequest_ScrapeResponse) isMetricsStreamRequest_Msg() {}

type MetricsRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // Exporter CRD name (verified against the auth token by the server).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRegister) Reset() {
	*x = MetricsRegister{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRegister) ProtoMessage() {}

func (x *MetricsRegister) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRegister.ProtoReflect.Descriptor instead.
func (*MetricsRegister) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsRegister) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type MetricsScrapeResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MetricsText []byte                 `protobuf:"bytes,1,opt,name=metrics_text,json=metricsText,proto3" json:"metrics_text,omitempty"` // Optional generate_latest() OpenMetrics text (legacy / debug).
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // When the snapshot was taken.
	// DD-3 sidecar: in-memory registry dump so the hub can merge and filter
	// exemplars without parsing OpenMetrics text (prometheus/common cannot).
	Families      []*MetricsFamily `protobuf:"bytes,3,rep,name=families,proto3" json:"families,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsScrapeResponse) Reset() {
	*x = MetricsScrapeResponse{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsScrapeResponse) ProtoMessage() {}

func (x *MetricsScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsScrapeResponse.ProtoReflect.Descriptor instead.
func (*MetricsScrapeResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsScrapeResponse) GetMetricsText() []byte {
	if x != nil {
		return x.MetricsText
	}
	return nil
}

func (x *MetricsScrapeResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricsScrapeResponse) GetFamilies() []*MetricsFamily {
	if x != nil {
		return x.Families
	}
	return nil
}

// One label name/value pair on a sample or exemplar.
type MetricsLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // Label name.
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Label value.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsLabel) Reset() {
	*x = MetricsLabel{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsLabel) ProtoMessage() {}

func (x *MetricsLabel) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsLabel.ProtoReflect.Descriptor instead.
func (*MetricsLabel) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsLabel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricsLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// OpenMetrics exemplar attached to a sample (JEP-0013 allowlist applied on the hub).
type MetricsExemplar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*MetricsLabel        `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`       // Exemplar labels (client, lease_id, …).
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`       // Exemplar observation value.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Optional exemplar timestamp.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsExemplar) Reset() {
	*x = MetricsExemplar{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsExemplar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsExemplar) ProtoMessage() {}

func (x *MetricsExemplar) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsExemplar.ProtoReflect.Descriptor instead.
func (*MetricsExemplar) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsExemplar) GetLabels() []*MetricsLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricsExemplar) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricsExemplar) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// One collected sample from prometheus_client (including histogram _bucket/_sum/_count).
type MetricsSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Sample name (may include _bucket, _sum, _count).
	Labels        []*MetricsLabel        `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`     // Sample labels (histogram buckets include le).
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`     // Sample value.
	Exemplar      *MetricsExemplar       `protobuf:"bytes,4,opt,name=exemplar,proto3" json:"exemplar,omitempty"` // Optional exemplar for this sample.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSample) Reset() {
	*x = MetricsSample{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSample) ProtoMessage() {}

func (x *MetricsSample) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSample.ProtoReflect.Descriptor instead.
func (*MetricsSample) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricsSample) GetLabels() []*MetricsLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricsSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricsSample) GetExemplar() *MetricsExemplar {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

// One metric family from CollectorRegistry.collect().
type MetricsFamily struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // Family name (counters include _total; no _bucket/_sum/_count).
	Help          string                 `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`                                  // Help text.
	Type          MetricsType            `protobuf:"varint,3,opt,name=type,proto3,enum=jumpstarter.v1.MetricsType" json:"type,omitempty"` // Family type.
	Samples       []*MetricsSample       `protobuf:"bytes,4,rep,name=samples,proto3" json:"samples,omitempty"`                            // Collected samples, including exemplars.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsFamily) Reset() {
	*x = MetricsFamily{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsFamily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsFamily) ProtoMessage() {}

func (x *MetricsFamily) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsFamily.ProtoReflect.Descriptor instead.
func (*MetricsFamily) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsFamily) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricsFamily) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *MetricsFamily) GetType() MetricsType {
	if x != nil {
		return x.Type
	}
	return MetricsType_METRICS_TYPE_UNSPECIFIED
}

func (x *MetricsFamily) GetSamples() []*MetricsSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// Telemetry → Exporter
type MetricsStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MetricsStreamResponse_ScrapeRequest
	Msg           isMetricsStreamResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsStreamResponse) Reset() {
	*x = MetricsStreamResponse{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsStreamResponse) ProtoMessage() {}

func (x *MetricsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsStreamResponse.ProtoReflect.Descriptor instead.
func (*MetricsStreamResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsStreamResponse) GetMsg() isMetricsStreamResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MetricsStreamResponse) GetScrapeRequest() *MetricsScrapeRequest {
	if x != nil {
		if x, ok := x.Msg.(*MetricsStreamResponse_ScrapeRequest); ok {
			return x.ScrapeRequest
		}
	}
	return nil
}

type isMetricsStreamResponse_Msg interface {
	isMetricsStreamResponse_Msg()
}

type MetricsStreamResponse_ScrapeRequest struct {
	ScrapeRequest *MetricsScrapeRequest `protobuf:"bytes,1,opt,name=scrape_request,json=scrapeRequest,proto3,oneof"`
}

func (*MetricsStreamResponse_ScrapeRequest) isMetricsStreamResponse_Msg() {}

// Empty request: "send your /metrics now".
type MetricsScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsScrapeRequest) Reset() {
	*x = MetricsScrapeRequest{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsScrapeRequest) ProtoMessage() {}

func (x *MetricsScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsScrapeRequest.ProtoReflect.Descriptor instead.
func (*MetricsScrapeRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

// Request to push log entries to the telemetry service.
type PushLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // Log entries to push.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogsRequest) Reset() {
	*x = PushLogsRequest{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogsRequest) ProtoMessage() {}

func (x *PushLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogsRequest.ProtoReflect.Descriptor instead.
func (*PushLogsRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *PushLogsRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Response to a PushLogs request.
type PushLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // Number of entries accepted.
	Dropped       uint32                 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`   // Number of entries dropped (backpressure).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogsResponse) Reset() {
	*x = PushLogsResponse{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogsResponse) ProtoMessage() {}

func (x *PushLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogsResponse.ProtoReflect.Descriptor instead.
func (*PushLogsResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *PushLogsResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *PushLogsResponse) GetDropped() uint32 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

// A structured log entry from an exporter or client.
// Maps directly to a Loki log entry with stream labels and body fields.
type LogEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                   // When the log was emitted.
	Severity    string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                                     // Log severity: debug, info, warning, error, critical.
	Message     string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                                                       // Human-readable log message.
	Component   string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`                                                                                                   // Loki stream label: cli, exporter, controller, router, telemetry.
	Exporter    string                 `protobuf:"bytes,5,opt,name=exporter,proto3" json:"exporter,omitempty"`                                                                                                     // Loki stream label: exporter CRD name (bounded by cluster size).
	Lease       string                 `protobuf:"bytes,6,opt,name=lease,proto3" json:"lease,omitempty"`                                                                                                           // Log body only (high cardinality): active lease name.
	Client      string                 `protobuf:"bytes,7,opt,name=client,proto3" json:"client,omitempty"`                                                                                                         // Log body only (high cardinality): client CRD name.
	Operation   string                 `protobuf:"bytes,8,opt,name=operation,proto3" json:"operation,omitempty"`                                                                                                   // Log body: operation name (flash, power, etc.).
	Result      string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`                                                                                                         // Log body: operation outcome (success, failure, etc.).
	DriverType  string                 `protobuf:"bytes,10,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`                                                                              // Log body: driver category (storage, power, network, etc.).
	ExtraFields map[string]string      `protobuf:"bytes,11,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional structured key-value fields.
	// Capped at 16 entries, 64-char keys, 256-char values.
	Namespace     string `protobuf:"bytes,12,opt,name=namespace,proto3" json:"namespace,omitempty"` // Loki stream label: Kubernetes namespace (bounded by cluster size).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{11}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogEntry) GetExporter() string {
	if x != nil {
		return x.Exporter
	}
	return ""
}

func (x *LogEntry) GetLease() string {
	if x != nil {
		return x.Lease
	}
	return ""
}

func (x *LogEntry) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *LogEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LogEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *LogEntry) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *LogEntry) GetExtraFields() map[string]string {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

func (x *LogEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_jumpstarter_v1_telemetry_proto protoreflect.FileDescriptor

const file_jumpstarter_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ejumpstarter/v1/telemetry.proto\x12\x0ejumpstarter.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x14MetricsStreamRequest\x12=\n" +
	"\bregister\x18\x01 \x01(\v2\x1f.jumpstarter.v1.MetricsRegisterH\x00R\bregister\x12P\n" +
	"\x0fscrape_response\x18\x02 \x01(\v2%.jumpstarter.v1.MetricsScrapeResponseH\x00R\x0escrapeResponseB\x05\n" +
	"\x03msg\"-\n" +
	"\x0fMetricsRegister\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\xaf\x01\n" +
	"\x15MetricsScrapeResponse\x12!\n" +
	"\fmetrics_text\x18\x01 \x01(\fR\vmetricsText\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\bfamilies\x18\x03 \x03(\v2\x1d.jumpstarter.v1.MetricsFamilyR\bfamilies\"8\n" +
	"\fMetricsLabel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x97\x01\n" +
	"\x0fMetricsExemplar\x124\n" +
	"\x06labels\x18\x01 \x03(\v2\x1c.jumpstarter.v1.MetricsLabelR\x06labels\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xac\x01\n" +
	"\rMetricsSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06labels\x18\x02 \x03(\v2\x1c.jumpstarter.v1.MetricsLabelR\x06labels\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12;\n" +
	"\bexemplar\x18\x04 \x01(\v2\x1f.jumpstarter.v1.MetricsExemplarR\bexemplar\"\xa1\x01\n" +
	"\rMetricsFamily\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04help\x18\x02 \x01(\tR\x04help\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.jumpstarter.v1.MetricsTypeR\x04type\x127\n" +
	"\asamples\x18\x04 \x03(\v2\x1d.jumpstarter.v1.MetricsSampleR\asamples\"m\n" +
	"\x15MetricsStreamResponse\x12M\n" +
	"\x0escrape_request\x18\x01 \x01(\v2$.jumpstarter.v1.MetricsScrapeRequestH\x00R\rscrapeRequestB\x05\n" +
	"\x03msg\"\x16\n" +
	"\x14MetricsScrapeRequest\"E\n" +
	"\x0fPushLogsRequest\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.jumpstarter.v1.LogEntryR\aentries\"H\n" +
	"\x10PushLogsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12\x18\n" +
	"\adropped\x18\x02 \x01(\rR\adropped\"\xe5\x03\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bexporter\x18\x05 \x01(\tR\bexporter\x12\x14\n" +
	"\x05lease\x18\x06 \x01(\tR\x05lease\x12\x16\n" +
	"\x06client\x18\a \x01(\tR\x06client\x12\x1c\n" +
	"\toperation\x18\b \x01(\tR\toperation\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x1f\n" +
	"\vdriver_type\x18\n" +
	" \x01(\tR\n" +
	"driverType\x12L\n" +
	"\fextra_fields\x18\v \x03(\v2).jumpstarter.v1.LogEntry.ExtraFieldsEntryR\vextraFields\x12\x1c\n" +
	"\tnamespace\x18\f \x01(\tR\tnamespace\x1a>\n" +
	"\x10ExtraFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xad\x01\n" +
	"\vMetricsType\x12\x1c\n" +
	"\x18METRICS_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14METRICS_TYPE_COUNTER\x10\x01\x12\x16\n" +
	"\x12METRICS_TYPE_GAUGE\x10\x02\x12\x1a\n" +
	"\x16METRICS_TYPE_HISTOGRAM\x10\x03\x12\x18\n" +
	"\x14METRICS_TYPE_SUMMARY\x10\x04\x12\x18\n" +
	"\x14METRICS_TYPE_UNTYPED\x10\x052\xc3\x01\n" +
	"\x10TelemetryService\x12`\n" +
	"\rMetricsStream\x12$.jumpstarter.v1.MetricsStreamRequest\x1a%.jumpstarter.v1.MetricsStreamResponse(\x010\x01\x12M\n" +
	"\bPushLogs\x12\x1f.jumpstarter.v1.PushLogsRequest\x1a .jumpstarter.v1.PushLogsResponseB\xdf\x01\n" +
	"\x12com.jumpstarter.v1B\x0eTelemetryProtoP\x01Z`github.com/jumpstarter-dev/jumpstarter/controller/internal/protocol/jumpstarter/v1;jumpstarterv1\xa2\x02\x03JXX\xaa\x02\x0eJumpstarter.V1\xca\x02\x0eJumpstarter\\V1\xe2\x02\x1aJumpstarter\\V1\\GPBMetadata\xea\x02\x0fJumpstarter::V1b\x06proto3"

var (
	file_jumpstarter_v1_telemetry_proto_rawDescOnce sync.Once
	file_jumpstarter_v1_telemetry_proto_rawDescData []byte
)

func file_jumpstarter_v1_telemetry_proto_rawDescGZIP() []byte {
	file_jumpstarter_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_jumpstarter_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_telemetry_proto_rawDesc), len(file_jumpstarter_v1_telemetry_proto_rawDesc)))
	})
	return file_jumpstarter_v1_telemetry_proto_rawDescData
}

var file_jumpstarter_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jumpstarter_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_jumpstarter_v1_telemetry_proto_goTypes = []any{
	(MetricsType)(0),              // 0: jumpstarter.v1.MetricsType
	(*MetricsStreamRequest)(nil),  // 1: jumpstarter.v1.MetricsStreamRequest
	(*MetricsRegister)(nil),       // 2: jumpstarter.v1.MetricsRegister
	(*MetricsScrapeResponse)(nil), // 3: jumpstarter.v1.MetricsScrapeResponse
	(*MetricsLabel)(nil),          // 4: jumpstarter.v1.MetricsLabel
	(*MetricsExemplar)(nil),       // 5: jumpstarter.v1.MetricsExemplar
	(*MetricsSample)(nil),         // 6: jumpstarter.v1.MetricsSample
	(*MetricsFamily)(nil),         // 7: jumpstarter.v1.MetricsFamily
	(*MetricsStreamResponse)(nil), // 8: jumpstarter.v1.MetricsStreamResponse
	(*MetricsScrapeRequest)(nil),  // 9: jumpstarter.v1.MetricsScrapeRequest
	(*PushLogsRequest)(nil),       // 10: jumpstarter.v1.PushLogsRequest
	(*PushLogsResponse)(nil),      // 11: jumpstarter.v1.PushLogsResponse
	(*LogEntry)(nil),              // 12: jumpstarter.v1.LogEntry
	nil,                           // 13: jumpstarter.v1.LogEntry.ExtraFieldsEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_jumpstarter_v1_telemetry_proto_depIdxs = []int32{
	2,  // 0: jumpstarter.v1.MetricsStreamRequest.register:type_name -> jumpstarter.v1.MetricsRegister
	3,  // 1: jumpstarter.v1.MetricsStreamRequest.scrape_response:type_name -> jumpstarter.v1.MetricsScrapeResponse
	14, // 2: jumpstarter.v1.MetricsScrapeResponse.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 3: jumpstarter.v1.MetricsScrapeResponse.families:type_name -> jumpstarter.v1.MetricsFamily
	4,  // 4: jumpstarter.v1.MetricsExemplar.labels:type_name -> jumpstarter.v1.MetricsLabel
	14, // 5: jumpstarter.v1.MetricsExemplar.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 6: jumpstarter.v1.MetricsSample.labels:type_name -> jumpstarter.v1.MetricsLabel
	5,  // 7: jumpstarter.v1.MetricsSample.exemplar:type_name -> jumpstarter.v1.MetricsExemplar
	0,  // 8: jumpstarter.v1.MetricsFamily.type:type_name -> jumpstarter.v1.MetricsType
	6,  // 9: jumpstarter.v1.MetricsFamily.samples:type_name -> jumpstarter.v1.MetricsSample
	9,  // 10: jumpstarter.v1.MetricsStreamResponse.scrape_request:type_name -> jumpstarter.v1.MetricsScrapeRequest
	12, // 11: jumpstarter.v1.PushLogsRequest.entries:type_name -> jumpstarter.v1.LogEntry
	14, // 12: jumpstarter.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	13, // 13: jumpstarter.v1.LogEntry.extra_fields:type_name -> jumpstarter.v1.LogEntry.ExtraFieldsEntry
	1,  // 14: jumpstarter.v1.TelemetryService.MetricsStream:input_type -> jumpstarter.v1.MetricsStreamRequest
	10, // 15: jumpstarter.v1.TelemetryService.PushLogs:input_type -> jumpstarter.v1.PushLogsRequest
	8,  // 16: jumpstarter.v1.TelemetryService.MetricsStream:output_type -> jumpstarter.v1.MetricsStreamResponse
	11, // 17: jumpstarter.v1.TelemetryService.PushLogs:output_type -> jumpstarter.v1.PushLogsResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_jumpstarter_v1_telemetry_proto_init() }
func file_jumpstarter_v1_telemetry_proto_init() {
	if File_jumpstarter_v1_telemetry_proto != nil {
		return
	}
	file_jumpstarter_v1_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*MetricsStreamRequest_Register)(nil),
		(*MetricsStreamRequest_ScrapeResponse)(nil),
	}
	file_jumpstarter_v1_telemetry_proto_msgTypes[7].OneofWrappers = []any{
		(*MetricsStreamResponse_ScrapeRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_telemetry_proto_rawDesc), len(file_jumpstarter_v1_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jumpstarter_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_jumpstarter_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_jumpstarter_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_jumpstarter_v1_telemetry_proto_msgTypes,
	}.Build()
	File_jumpstarter_v1_telemetry_proto = out.File
	file_jumpstarter_v1_telemetry_proto_goTypes = nil
	file_jumpstarter_v1_telemetry_proto_depIdxs = nil
}
