// Copyright 2024 The Jumpstarter Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jumpstarter/v1/telemetry.proto

package jumpstarterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to push log entries to the telemetry service.
type PushLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // Log entries to push.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogsRequest) Reset() {
	*x = PushLogsRequest{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogsRequest) ProtoMessage() {}

func (x *PushLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogsRequest.ProtoReflect.Descriptor instead.
func (*PushLogsRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *PushLogsRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Response to a PushLogs request.
type PushLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // Number of entries accepted.
	Dropped       uint32                 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`   // Number of entries dropped (backpressure).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogsResponse) Reset() {
	*x = PushLogsResponse{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogsResponse) ProtoMessage() {}

func (x *PushLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogsResponse.ProtoReflect.Descriptor instead.
func (*PushLogsResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *PushLogsResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *PushLogsResponse) GetDropped() uint32 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

// A structured log entry from an exporter or client.
// Maps directly to a Loki log entry with stream labels and body fields.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                   // When the log was emitted.
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                                     // Log severity: debug, info, warning, error, critical.
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                                                       // Human-readable log message.
	Component     string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`                                                                                                   // Loki stream label: cli, exporter, controller, router, telemetry.
	Exporter      string                 `protobuf:"bytes,5,opt,name=exporter,proto3" json:"exporter,omitempty"`                                                                                                     // Loki stream label: exporter CRD name (bounded by cluster size).
	Lease         string                 `protobuf:"bytes,6,opt,name=lease,proto3" json:"lease,omitempty"`                                                                                                           // Log body only (high cardinality): active lease name.
	Client        string                 `protobuf:"bytes,7,opt,name=client,proto3" json:"client,omitempty"`                                                                                                         // Log body only (high cardinality): client CRD name.
	Operation     string                 `protobuf:"bytes,8,opt,name=operation,proto3" json:"operation,omitempty"`                                                                                                   // Log body: operation name (flash, power, etc.).
	Result        string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`                                                                                                         // Log body: operation outcome (success, failure, etc.).
	DriverType    string                 `protobuf:"bytes,10,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`                                                                              // Log body: driver category (storage, power, network, etc.).
	ExtraFields   map[string]string      `protobuf:"bytes,11,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional structured key-value fields.
	Namespace     string                 `protobuf:"bytes,12,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                                                                  // Loki stream label: Kubernetes namespace (bounded by cluster size).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogEntry) GetExporter() string {
	if x != nil {
		return x.Exporter
	}
	return ""
}

func (x *LogEntry) GetLease() string {
	if x != nil {
		return x.Lease
	}
	return ""
}

func (x *LogEntry) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *LogEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LogEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *LogEntry) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *LogEntry) GetExtraFields() map[string]string {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

func (x *LogEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_jumpstarter_v1_telemetry_proto protoreflect.FileDescriptor

const file_jumpstarter_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ejumpstarter/v1/telemetry.proto\x12\x0ejumpstarter.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x0fPushLogsRequest\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.jumpstarter.v1.LogEntryR\aentries\"H\n" +
	"\x10PushLogsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12\x18\n" +
	"\adropped\x18\x02 \x01(\rR\adropped\"\xe5\x03\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bexporter\x18\x05 \x01(\tR\bexporter\x12\x14\n" +
	"\x05lease\x18\x06 \x01(\tR\x05lease\x12\x16\n" +
	"\x06client\x18\a \x01(\tR\x06client\x12\x1c\n" +
	"\toperation\x18\b \x01(\tR\toperation\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x1f\n" +
	"\vdriver_type\x18\n" +
	" \x01(\tR\n" +
	"driverType\x12L\n" +
	"\fextra_fields\x18\v \x03(\v2).jumpstarter.v1.LogEntry.ExtraFieldsEntryR\vextraFields\x12\x1c\n" +
	"\tnamespace\x18\f \x01(\tR\tnamespace\x1a>\n" +
	"\x10ExtraFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012a\n" +
	"\x10TelemetryService\x12M\n" +
	"\bPushLogs\x12\x1f.jumpstarter.v1.PushLogsRequest\x1a .jumpstarter.v1.PushLogsResponseB\xdf\x01\n" +
	"\x12com.jumpstarter.v1B\x0eTelemetryProtoP\x01Z`github.com/jumpstarter-dev/jumpstarter/controller/internal/protocol/jumpstarter/v1;jumpstarterv1\xa2\x02\x03JXX\xaa\x02\x0eJumpstarter.V1\xca\x02\x0eJumpstarter\\V1\xe2\x02\x1aJumpstarter\\V1\\GPBMetadata\xea\x02\x0fJumpstarter::V1b\x06proto3"

var (
	file_jumpstarter_v1_telemetry_proto_rawDescOnce sync.Once
	file_jumpstarter_v1_telemetry_proto_rawDescData []byte
)

func file_jumpstarter_v1_telemetry_proto_rawDescGZIP() []byte {
	file_jumpstarter_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_jumpstarter_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_telemetry_proto_rawDesc), len(file_jumpstarter_v1_telemetry_proto_rawDesc)))
	})
	return file_jumpstarter_v1_telemetry_proto_rawDescData
}

var file_jumpstarter_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jumpstarter_v1_telemetry_proto_goTypes = []any{
	(*PushLogsRequest)(nil),       // 0: jumpstarter.v1.PushLogsRequest
	(*PushLogsResponse)(nil),      // 1: jumpstarter.v1.PushLogsResponse
	(*LogEntry)(nil),              // 2: jumpstarter.v1.LogEntry
	nil,                           // 3: jumpstarter.v1.LogEntry.ExtraFieldsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_jumpstarter_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: jumpstarter.v1.PushLogsRequest.entries:type_name -> jumpstarter.v1.LogEntry
	4, // 1: jumpstarter.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: jumpstarter.v1.LogEntry.extra_fields:type_name -> jumpstarter.v1.LogEntry.ExtraFieldsEntry
	0, // 3: jumpstarter.v1.TelemetryService.PushLogs:input_type -> jumpstarter.v1.PushLogsRequest
	1, // 4: jumpstarter.v1.TelemetryService.PushLogs:output_type -> jumpstarter.v1.PushLogsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jumpstarter_v1_telemetry_proto_init() }
func file_jumpstarter_v1_telemetry_proto_init() {
	if File_jumpstarter_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_telemetry_proto_rawDesc), len(file_jumpstarter_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jumpstarter_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_jumpstarter_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_jumpstarter_v1_telemetry_proto_msgTypes,
	}.Build()
	File_jumpstarter_v1_telemetry_proto = out.File
	file_jumpstarter_v1_telemetry_proto_goTypes = nil
	file_jumpstarter_v1_telemetry_proto_depIdxs = nil
}
