# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import jumpstarter_pb2 as jumpstarter_dot_v1_dot_jumpstarter__pb2


class ControllerServiceStub:
    """A service where an exporter can connect to make itself available.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/Register',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RegisterRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/Unregister',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/ReportStatus',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReportStatusRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReportStatusResponse.FromString,
                _registered_method=True)
        self.Listen = channel.unary_stream(
                '/jumpstarter.v1.ControllerService/Listen',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListenRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListenResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_stream(
                '/jumpstarter.v1.ControllerService/Status',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StatusRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Dial = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/Dial',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DialRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DialResponse.FromString,
                _registered_method=True)
        self.GetLease = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/GetLease',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetLeaseRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetLeaseResponse.FromString,
                _registered_method=True)
        self.RequestLease = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/RequestLease',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RequestLeaseRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RequestLeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/ReleaseLease',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReleaseLeaseRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReleaseLeaseResponse.FromString,
                _registered_method=True)
        self.ListLeases = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/ListLeases',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListLeasesRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListLeasesResponse.FromString,
                _registered_method=True)
        self.GetServiceEndpoints = channel.unary_unary(
                '/jumpstarter.v1.ControllerService/GetServiceEndpoints',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetServiceEndpointsRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetServiceEndpointsResponse.FromString,
                _registered_method=True)


class ControllerServiceServicer:
    """A service where an exporter can connect to make itself available.
    """

    def Register(self, request, context):
        """Register an exporter with the controller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister an exporter from the controller.
        Disconnecting will invalidate any existing router tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """Report exporter status to the controller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listen(self, request, context):
        """Listen for incoming client connections on a lease.
        Returns stream tokens for accepting incoming client connections.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Stream lease status updates for the exporter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dial(self, request, context):
        """Dial an exporter through the router.
        Returns a stream token for connecting to the desired exporter.
        Leases are checked before token issuance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLease(self, request, context):
        """Retrieve a lease by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestLease(self, request, context):
        """Request a new lease for an exporter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Release an active lease.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLeases(self, request, context):
        """List all leases.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceEndpoints(self, request, context):
        """Discover optional service endpoints (e.g. telemetry).
        Exporters and clients call this after registration to find the telemetry service.
        Returns an empty list when no optional services are deployed.
        Older controllers return UNIMPLEMENTED; callers must treat that as an empty list.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RegisterRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RegisterResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.UnregisterRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.UnregisterResponse.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReportStatusRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReportStatusResponse.SerializeToString,
            ),
            'Listen': grpc.unary_stream_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListenRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListenResponse.SerializeToString,
            ),
            'Status': grpc.unary_stream_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StatusRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StatusResponse.SerializeToString,
            ),
            'Dial': grpc.unary_unary_rpc_method_handler(
                    servicer.Dial,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DialRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DialResponse.SerializeToString,
            ),
            'GetLease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLease,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetLeaseRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetLeaseResponse.SerializeToString,
            ),
            'RequestLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestLease,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RequestLeaseRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.RequestLeaseResponse.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReleaseLeaseRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ReleaseLeaseResponse.SerializeToString,
            ),
            'ListLeases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLeases,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListLeasesRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ListLeasesResponse.SerializeToString,
            ),
            'GetServiceEndpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceEndpoints,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetServiceEndpointsRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetServiceEndpointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jumpstarter.v1.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jumpstarter.v1.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService:
    """A service where an exporter can connect to make itself available.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/Register',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.RegisterRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/Unregister',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.UnregisterRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/ReportStatus',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ReportStatusRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ReportStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jumpstarter.v1.ControllerService/Listen',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ListenRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ListenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jumpstarter.v1.ControllerService/Status',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.StatusRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/Dial',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.DialRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.DialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/GetLease',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.GetLeaseRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.GetLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/RequestLease',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.RequestLeaseRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.RequestLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/ReleaseLease',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ReleaseLeaseRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ReleaseLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLeases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/ListLeases',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ListLeasesRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ListLeasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceEndpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ControllerService/GetServiceEndpoints',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.GetServiceEndpointsRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.GetServiceEndpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExporterServiceStub:
    """A service an exporter can share locally to be used without a server.
    Channel and call credentials are used to authenticate the client and route to the right exporter.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReport = channel.unary_unary(
                '/jumpstarter.v1.ExporterService/GetReport',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetReportResponse.FromString,
                _registered_method=True)
        self.DriverCall = channel.unary_unary(
                '/jumpstarter.v1.ExporterService/DriverCall',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DriverCallRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DriverCallResponse.FromString,
                _registered_method=True)
        self.StreamingDriverCall = channel.unary_stream(
                '/jumpstarter.v1.ExporterService/StreamingDriverCall',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StreamingDriverCallRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StreamingDriverCallResponse.FromString,
                _registered_method=True)
        self.LogStream = channel.unary_stream(
                '/jumpstarter.v1.ExporterService/LogStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.LogStreamResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/jumpstarter.v1.ExporterService/Reset',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ResetRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/jumpstarter.v1.ExporterService/GetStatus',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/jumpstarter.v1.ExporterService/EndSession',
                request_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.EndSessionResponse.FromString,
                _registered_method=True)


class ExporterServiceServicer:
    """A service an exporter can share locally to be used without a server.
    Channel and call credentials are used to authenticate the client and route to the right exporter.
    """

    def GetReport(self, request, context):
        """Retrieve the exporter driver report.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriverCall(self, request, context):
        """Invoke a method on a driver instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingDriverCall(self, request, context):
        """Invoke a streaming method on a driver instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogStream(self, request, context):
        """Stream log messages from the exporter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the exporter connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Retrieve the current exporter status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """End the current session, triggering the afterLease hook.
        The client should keep the connection open to receive hook logs via LogStream.
        Returns after the afterLease hook completes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExporterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReport,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetReportResponse.SerializeToString,
            ),
            'DriverCall': grpc.unary_unary_rpc_method_handler(
                    servicer.DriverCall,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DriverCallRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.DriverCallResponse.SerializeToString,
            ),
            'StreamingDriverCall': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamingDriverCall,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StreamingDriverCallRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.StreamingDriverCallResponse.SerializeToString,
            ),
            'LogStream': grpc.unary_stream_rpc_method_handler(
                    servicer.LogStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.LogStreamResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ResetRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.ResetResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetStatusRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.GetStatusResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.EndSessionRequest.FromString,
                    response_serializer=jumpstarter_dot_v1_dot_jumpstarter__pb2.EndSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jumpstarter.v1.ExporterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jumpstarter.v1.ExporterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExporterService:
    """A service an exporter can share locally to be used without a server.
    Channel and call credentials are used to authenticate the client and route to the right exporter.
    """

    @staticmethod
    def GetReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ExporterService/GetReport',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.GetReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DriverCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ExporterService/DriverCall',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.DriverCallRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.DriverCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamingDriverCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jumpstarter.v1.ExporterService/StreamingDriverCall',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.StreamingDriverCallRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.StreamingDriverCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jumpstarter.v1.ExporterService/LogStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.LogStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ExporterService/Reset',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ResetRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ExporterService/GetStatus',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.GetStatusRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.v1.ExporterService/EndSession',
            jumpstarter_dot_v1_dot_jumpstarter__pb2.EndSessionRequest.SerializeToString,
            jumpstarter_dot_v1_dot_jumpstarter__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
