"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 The Jumpstarter Authors"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PushLogsRequest(google.protobuf.message.Message):
    """Request to push log entries to the telemetry service."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___LogEntry]:
        """Log entries to push."""

    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[Global___LogEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entries", b"entries"]) -> None: ...

Global___PushLogsRequest: typing_extensions.TypeAlias = PushLogsRequest

@typing.final
class PushLogsResponse(google.protobuf.message.Message):
    """Response to a PushLogs request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: builtins.int
    DROPPED_FIELD_NUMBER: builtins.int
    accepted: builtins.int
    """Number of entries accepted."""
    dropped: builtins.int
    """Number of entries dropped (backpressure)."""
    def __init__(
        self,
        *,
        accepted: builtins.int = ...,
        dropped: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accepted", b"accepted", "dropped", b"dropped"]) -> None: ...

Global___PushLogsResponse: typing_extensions.TypeAlias = PushLogsResponse

@typing.final
class LogEntry(google.protobuf.message.Message):
    """A structured log entry from an exporter or client.
    Maps directly to a Loki log entry with stream labels and body fields.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ExtraFieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TIMESTAMP_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    COMPONENT_FIELD_NUMBER: builtins.int
    EXPORTER_FIELD_NUMBER: builtins.int
    LEASE_FIELD_NUMBER: builtins.int
    CLIENT_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    DRIVER_TYPE_FIELD_NUMBER: builtins.int
    EXTRA_FIELDS_FIELD_NUMBER: builtins.int
    severity: builtins.str
    """Log severity: debug, info, warning, error, critical."""
    message: builtins.str
    """Human-readable log message."""
    component: builtins.str
    """Loki stream label: cli, exporter, controller, router, telemetry."""
    exporter: builtins.str
    """Loki stream label: exporter CRD name (bounded by cluster size)."""
    lease: builtins.str
    """Log body only (high cardinality): active lease name."""
    client: builtins.str
    """Log body only (high cardinality): client CRD name."""
    operation: builtins.str
    """Log body: operation name (flash, power, etc.)."""
    result: builtins.str
    """Log body: operation outcome (success, failure, etc.)."""
    driver_type: builtins.str
    """Log body: driver category (storage, power, network, etc.)."""
    namespace: builtins.str
    """Loki stream label: Kubernetes namespace (bounded by cluster size)."""
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """When the log was emitted."""

    @property
    def extra_fields(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Additional structured key-value fields."""

    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        severity: builtins.str = ...,
        message: builtins.str = ...,
        component: builtins.str = ...,
        exporter: builtins.str = ...,
        lease: builtins.str = ...,
        client: builtins.str = ...,
        operation: builtins.str = ...,
        result: builtins.str = ...,
        driver_type: builtins.str = ...,
        extra_fields: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        namespace: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["client", b"client", "component", b"component", "driver_type", b"driver_type", "exporter", b"exporter", "extra_fields", b"extra_fields", "lease", b"lease", "message", b"message", "namespace", b"namespace", "operation", b"operation", "result", b"result", "severity", b"severity", "timestamp", b"timestamp"]) -> None: ...

Global___LogEntry: typing_extensions.TypeAlias = LogEntry
