"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 The Jumpstarter Authors"""

import abc
import collections.abc
import grpc
import grpc.aio
import jumpstarter.v1.telemetry_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_TelemetryServicePushLogsType = typing_extensions.TypeVar(
    '_TelemetryServicePushLogsType',
    grpc.UnaryUnaryMultiCallable[
        jumpstarter.v1.telemetry_pb2.PushLogsRequest,
        jumpstarter.v1.telemetry_pb2.PushLogsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        jumpstarter.v1.telemetry_pb2.PushLogsRequest,
        jumpstarter.v1.telemetry_pb2.PushLogsResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        jumpstarter.v1.telemetry_pb2.PushLogsRequest,
        jumpstarter.v1.telemetry_pb2.PushLogsResponse,
    ],
)

class TelemetryServiceStub(typing.Generic[_TelemetryServicePushLogsType]):
    """A service that receives structured logs from exporters and clients.
    Implemented by jumpstarter-telemetry; not part of the controller.
    """

    @typing.overload
    def __init__(self: TelemetryServiceStub[
        grpc.UnaryUnaryMultiCallable[
            jumpstarter.v1.telemetry_pb2.PushLogsRequest,
            jumpstarter.v1.telemetry_pb2.PushLogsResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: TelemetryServiceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            jumpstarter.v1.telemetry_pb2.PushLogsRequest,
            jumpstarter.v1.telemetry_pb2.PushLogsResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    PushLogs: _TelemetryServicePushLogsType
    """Push structured log entries to the telemetry service for Loki ingest."""

TelemetryServiceAsyncStub: typing_extensions.TypeAlias = TelemetryServiceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        jumpstarter.v1.telemetry_pb2.PushLogsRequest,
        jumpstarter.v1.telemetry_pb2.PushLogsResponse,
    ],
]

class TelemetryServiceServicer(metaclass=abc.ABCMeta):
    """A service that receives structured logs from exporters and clients.
    Implemented by jumpstarter-telemetry; not part of the controller.
    """

    @abc.abstractmethod
    def PushLogs(
        self,
        request: jumpstarter.v1.telemetry_pb2.PushLogsRequest,
        context: _ServicerContext,
    ) -> typing.Union[jumpstarter.v1.telemetry_pb2.PushLogsResponse, collections.abc.Awaitable[jumpstarter.v1.telemetry_pb2.PushLogsResponse]]:
        """Push structured log entries to the telemetry service for Loki ingest."""

def add_TelemetryServiceServicer_to_server(servicer: TelemetryServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
