---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates/status
  - clusterissuers/status
  - issuers/status
  verbs:
  - get
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients
  - exporteraccesspolicies
  - exporters
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients/finalizers
  - exporteraccesspolicies/finalizers
  - exporters/finalizers
  - leases/finalizers
  verbs:
  - update
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients/status
  - exporteraccesspolicies/status
  - exporters/status
  - leases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.jumpstarter.dev
  resources:
  - jumpstarters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.jumpstarter.dev
  resources:
  - jumpstarters/finalizers
  verbs:
  - update
- apiGroups:
  - operator.jumpstarter.dev
  resources:
  - jumpstarters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - virtualtarget.jumpstarter.dev
  resources:
  - exportersets
  - virtualtargetclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virtualtarget.jumpstarter.dev
  resources:
  - exportersets/finalizers
  verbs:
  - update
- apiGroups:
  - virtualtarget.jumpstarter.dev
  resources:
  - exportersets/scale
  - exportersets/status
  verbs:
  - get
  - patch
  - update
