name: Build and push buildroot-based flasher OCI bundle

on:
  workflow_dispatch:

jobs:
  build-fits:
    runs-on: ubuntu-24.04-arm
    container: registry.fedoraproject.org/fedora:44
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Run build_fits.sh
        run: |
          cd python/packages/jumpstarter-driver-flashers/oci_bundles/aarch64-itb
          ./build_fits.sh

      - name: Upload FIT artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: FIT-images
          path: python/packages/jumpstarter-driver-flashers/oci_bundles/aarch64-itb/data/*.itb

      - name: Run build_bundle.sh for aarch64-itb
        run: |
          cd python/packages/jumpstarter-driver-flashers/oci_bundles && dnf install -y oras
          oras login quay.io -u jumpstarter-dev+jumpstarter_ci --password-stdin <<< "${{ secrets.QUAY_TOKEN }}"
          ./build_bundle.sh quay.io/jumpstarter-dev/jumpstarter-flasher-aarch64-itb:latest aarch64-itb
