name: Kind based CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'controller/**'

permissions:
  contents: read

jobs:
  deploy-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: controller/go.mod
          cache-dependency-path: |
            controller/go.sum
            controller/deploy/operator/go.sum

      - name: Run make deploy
        working-directory: controller
        run: make deploy-ci -j4 --output-sync=target

  e2e-test-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: controller/go.mod
          cache-dependency-path: |
            controller/go.sum
            controller/deploy/operator/go.sum

      - name: Run operator e2e test
        working-directory: controller
        run: make test-operator-e2e-ci -j4 --output-sync=target
